inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails


AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

Rails:
  Enabled: true

AsciiComments:
  Enabled: false

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Exclude:
    - 'spec/**/*'
  Max: 121

Naming/MethodParameterName:
  Exclude:
    - 'app/controllers/application_controller.rb'

Naming/VariableNumber:
  Exclude:
    - 'app/controllers/application_controller.rb'