version: "3"
services:
  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/LYbody
      - bundle_path:/bundle
      - public-data:/LYbody/public
      - tmp-data:/LYbody/tmp
      - log-data:/var/log/nginx
    environment:
      - BUNDLE_PATH=/bundle
    tty: true
    stdin_open: true
    depends_on:
      - chrome
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - db-data:/var/lib/mysql

  # RSpec記述の為に使用
  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 256m
    ports:
      - 4444:4444

  nginx:
    build: ./nginx_docker
    volumes:
      - public-data:/LYbody/public
      - tmp-data:/LYbody/tmp
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  bundle_path:
  public-data:
  tmp-data:
  log-data:
  db-data:
