version: '3'
services:
  web:
    build: .
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/LYbody
      - public-data:/LYbody/public
      - tmp-data:/LYbody/tmp
      - log-data:/var/log/nginx
    tty: true
    stdin_open: true

  nginx:
    build: ./nginx_docker
    volumes:
      - public-data:/LYbody/public
      - tmp-data:/LYbody/tmp
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: